# Generated by Django 3.2.13 on 2022-05-23 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileUser', '0002_auto_20220523_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Called',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('situation', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'In Progress')], verbose_name='Situation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profileUser.profileuser', verbose_name='profile')),
            ],
        ),
    ]
