# Generated by Django 3.2.13 on 2022-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='called',
            name='title',
            field=models.CharField(default=1, max_length=300, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
