# Generated by Django 3.2.13 on 2022-05-25 02:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220525_0248'),
        ('profileUser', '0005_auto_20220525_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='Rua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='cep',
            field=models.CharField(default=1, max_length=200, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='city',
            field=models.CharField(default=1, max_length=200, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='district',
            field=models.CharField(default=1, max_length=200, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number',
            field=models.CharField(default=1, max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='service_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='services.serviceplan', verbose_name='Service Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='theme_dark',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Theme Dark'),
        ),
    ]
