# Generated by Django 3.2.13 on 2022-06-06 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220525_0248'),
        ('profileUser', '0006_auto_20220525_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='service_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.serviceplan', verbose_name='Plano de Serviço'),
        ),
    ]
