# Generated by Django 3.2.13 on 2022-05-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Plan Value')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('type_service', models.IntegerField(choices=[(0, 'Internet'), (1, 'Voip')], verbose_name='Type Service')),
                ('velocity', models.IntegerField(blank=True, null=True, verbose_name='Velocity')),
                ('bandwidth', models.IntegerField(blank=True, null=True, verbose_name='Bandwidth')),
            ],
        ),
    ]
