# Generated by Django 3.2.13 on 2022-05-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220525_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='bandwidth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bandwidth'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='description',
            field=models.CharField(default=1, max_length=300, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='type_service',
            field=models.IntegerField(choices=[(0, 'Internet'), (1, 'Voip')], default=1, verbose_name='Type Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Plan Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='velocity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Velocity'),
        ),
    ]
