# Generated by Django 3.2.13 on 2022-05-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20220525_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Value'),
            preserve_default=False,
        ),
    ]
