# Generated by Django 3.2.13 on 2022-06-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_contas_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='payment',
            field=models.IntegerField(blank=True, choices=[(0, 'Card'), (1, 'Bank Ticket'), (2, 'Pix'), (3, 'Bank Transfer')], null=True, verbose_name='Payment'),
        ),
    ]
