# Generated by Django 3.2.13 on 2022-06-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_contas_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='profile',
        ),
    ]
