# Generated by Django 3.2.13 on 2022-06-15 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_paymentreceipt_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='payment_receipt',
        ),
        migrations.DeleteModel(
            name='PaymentReceipt',
        ),
    ]
