# Generated by Django 3.2.13 on 2022-06-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileUser', '0007_alter_profileuser_service_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='Conteúdo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profileUser.profileuser', verbose_name='profile')),
            ],
        ),
    ]
