# Generated by Django 3.2.13 on 2022-06-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='project',
            new_name='profile',
        ),
    ]
